 MySQL Script generated by MySQL Workbench
-- Tue Jun 13 14:02:06 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema huberteats
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `huberteats` ;

-- -----------------------------------------------------
-- Schema huberteats
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `huberteats` DEFAULT CHARACTER SET utf8 ;
USE `huberteats` ;

-- -----------------------------------------------------
-- Table `huberteats`.`menus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `huberteats`.`menus` ;

CREATE TABLE IF NOT EXISTS `huberteats`.`menus` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `huberteats`.`recipes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `huberteats`.`recipes` ;

CREATE TABLE IF NOT EXISTS `huberteats`.`recipes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `description` LONGTEXT NULL,
  `img_url` VARCHAR(255) NULL,
  `ingredients` LONGTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `huberteats`.`table3`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `huberteats`.`table3` ;

CREATE TABLE IF NOT EXISTS `huberteats`.`table3` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `huberteats`.`menus_recipes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `huberteats`.`menus_recipes` ;

CREATE TABLE IF NOT EXISTS `huberteats`.`menus_recipes` (
  `menus_id` INT NOT NULL,
  `recipes_id` INT NOT NULL,
  PRIMARY KEY (`menus_id`, `recipes_id`),
  CONSTRAINT `fk_menus_has_recipes_menus`
    FOREIGN KEY (`menus_id`)
    REFERENCES `huberteats`.`menus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_menus_has_recipes_recipes1`
    FOREIGN KEY (`recipes_id`)
    REFERENCES `huberteats`.`recipes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_menu_has_recipes_recipes1_idx` ON `huberteats`.`menus_recipes` (`recipes_id` ASC) VISIBLE;

CREATE INDEX `fk_menu_has_recipes_menu_idx` ON `huberteats`.`menus_recipes` (`menus_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
